#!/bin/sh

if [ -z "${EIGION_HOME}" ]
then
  echo "EIGION_HOME is unset" 1>&2
  exit 1
fi

exec /usr/bin/env java \
-p "${EIGION_HOME}/lib" \
-m com.io7m.eigion.amberjack.cmdline/com.io7m.eigion.amberjack.cmdline.EIShellMain \
"$@"
