#!/bin/sh

if [ -z "${EIGION_SERVER_HOME}" ]
then
  echo "EIGION_SERVER_HOME is unset" 1>&2
  exit 1
fi

if [ -z "${EIGION_SERVER_LOG_DIRECTORY}" ]
then
  echo "EIGION_SERVER_LOG_DIRECTORY is unset" 1>&2
  exit 1
fi

exec /usr/bin/env java \
-p "${EIGION_SERVER_HOME}/lib" \
-m com.io7m.eigion.server.main/com.io7m.eigion.server.main.EIServerMain \
"$@"
