#!/bin/sh

if [ -z "${EIGION_PIKE_HOME}" ]
then
  echo "EIGION_PIKE_HOME is unset" 1>&2
  exit 1
fi

exec /usr/bin/env java \
-p "${EIGION_PIKE_HOME}/lib" \
-m com.io7m.eigion.pike.cmdline.main/com.io7m.eigion.pike.cmdline.main.EIShellMain \
"$@"
